# Generated by Django 3.2 on 2021-06-28 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogcore', '0008_auto_20210628_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='hits',
        ),
    ]
